export default {
  "retcode": 0,
  "message": "OK",
  "data": {
    "account": {
      "uid": "61",
      "name": "andromeda",
      "email": "andromeda",
      "mobile": "",
      "is_email_verify": 1,
      "realname": "",
      "identity_card": "",
      "token": "token",
      "safe_mobile": "",
      "facebook_name": "",
      "google_name": "",
      "twitter_name": "",
      "game_center_name": "",
      "apple_name": "",
      "sony_name": "",
      "tap_name": "",
      "country": "US",
      "reactivate_ticket": "",
      "area_code": "US",
      "device_grant_ticket": "",
      "steam_name": "",
    },
    "device_grant_required": false,
    "safe_mobile_required": false,
    "realperson_required": false,
    "realname_operation": "None",
  },
}